using System.ComponentModel.DataAnnotations;

namespace OrderService.DTOs;

/// <summary>
/// Represents the data required to create a new order.
/// The order identifier is generated by the database and is not accepted from the client.
/// </summary>
public class CreateOrderDto
{
    /// <summary>
    /// Gets or sets the name of the customer placing the order.
    /// </summary>
    [Required]
    [StringLength(200)]
    public string CustomerName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the name of the ordered product.
    /// </summary>
    [Required]
    [StringLength(200)]
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the number of product units. The value must be greater than zero.
    /// </summary>
    [Range(1, int.MaxValue)]
    public int Quantity { get; set; }

    /// <summary>
    /// Gets or sets the price per unit. The value must be greater than zero.
    /// </summary>
    [Range(0.01, double.MaxValue)]
    public decimal Price { get; set; }
}
